### ISSUE TITLE
Update to Slate 0.14.x

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/slate-edit-list#14]
In Slate 0.14.x, a PR was merged : https://github.com/ianstormtaylor/slate/pull/249

It adds useful, low-level transformation, that could simplify the current implementation (which relies heavily on `setNodeByKey` and sometimes even updates the selection by hand).

**Comment by mull** [comment]
The plugin is also broken in 0.14 :) Ran the test suite and checked if it was a quick thing to fix, but it wasn't (at least for me.) Quite a lot of errors.

**Comment by Soreine** [comment]
I had not even checked yet. Thanks for pointing it out :)

**Comment by Soreine** [comment]
It turns out it was only minor issues :) phew

**Comment by mull** [comment]
You make me *so* happy! I was just going to check whether or not you needed help with this! :D
