### ISSUE TITLE
Different plugin design: More flexibility with list types

### ISSUE THREAD

**Issue by ianstormtaylor** [GitbookIO/slate-edit-list#21]
Looking into adding lists to an editor I'm working on, and thinking about three types:

- ordered lists
- unordered lists
- check lists

And arguably there could be more that I'm not thinking about. It might be nice to refactor this plugin to make it less opinionated about the specific types of lists someone would use, and to instead just add the plugin multiple times, once for each list. Something like:

```js
const plugins = [
  EditList({
    listType: 'ordered_list',
    itemType: 'list_item',
    defaultType: 'paragraph'
  }),

  EditList({
    listType: 'unordered_list',
    itemType: 'list_item',
    defaultType: 'paragraph'
  }),

  EditList({
    listType: 'check_list',
    itemType: 'check_list_item',
    defaultType: 'paragraph'
  }),

   ...
]
```

Just a thought for flexibility.

**Comment by Soreine** [comment]
It may not be obvious, but the current architecture can be actually used the way you suggest. You just have to not use the `typeOL` option and the related utils.

**Comment by Soreine** [comment]
Well, actually if the different list types you need to support can be nested indifferently (checklist inside inside ordered list etc.), the plugin needs to be aware of them. Maybe the options for the plugins should be as follow:

```
listTypes: Array<String> // All possible types of lists
itemType: String // Only one generic type of item
```
