### ISSUE TITLE
Backspace Bug

### ISSUE THREAD

**Issue by eugenkiss** [GitbookIO/slate-edit-list#26]
The following steps result in an exception:

1. Create a list node
2. Press Shift+Enter to insert a break inside the list node
3. Press Backspace

Here's a gomix for reproduction: 
* https://big-keeper.gomix.me
* https://gomix.com/#!/project/big-keeper

Here's a video: https://streamable.com/7o4xz

**Comment by Soreine** [comment]
Added a failing test to Slate https://github.com/ianstormtaylor/slate/pull/524

**Comment by Soreine** [comment]
Waiting for merge https://github.com/ianstormtaylor/slate/pull/594
