### ISSUE TITLE
Indentation Bug (Reordering)

### ISSUE THREAD

**Issue by eugenkiss** [GitbookIO/slate-edit-list#27]
Indent list items one after the other as shown in this video: https://streamable.com/97t26

When you indent number 5 it jumps into the wrong position. The same is true for the following list items.

Here's a gomix for reproduction: 
* https://big-keeper.gomix.me
* https://gomix.com/#!/project/big-keeper

**Comment by Soreine** [comment]
Thank you, this is fixed in 0.5.6 ! Your indication on how to reproduce were very welcome :D
