### ISSUE TITLE
Unintuitive Caret Behavior (New List Item with Inline Node)

### ISSUE THREAD

**Issue by eugenkiss** [GitbookIO/slate-edit-list#29]
Consider the following situation:

```
* text<caret>link
```

After pressing `Enter` I expect the following to happen:

```
* text
* <caret>link
```

Instead, the following happens:

```
* text<caret>
* link
```

Here's a video illustrating the problem: https://streamable.com/fk7wi

Here's a gomix for reproduction: 
* https://noxious-ashtray.gomix.me/
* https://gomix.com/#!/project/noxious-ashtray

**Comment by Soreine** [comment]
This should be fixed
