### ISSUE TITLE
unexpected tab behavior

### ISSUE THREAD

**Issue by ianstormtaylor** [GitbookIO/slate-edit-list#3]
Hey @SamyPesse !

Just installed this plugin to handle lists in my editor, and I ran into unexpected tab behavior. What I assumed would happen is (based on editors like Dropbox Paper or Notion):
- On `tab`, any list items in the selection are indented by one, regardless of whether it's collapsed or not, and whether it's at the start or end of the block.
- On `shift-tab`, any list items in the selection are unindented by one.
- You can't `tab` to create a new list item from a paragraph.
- You can't `shift-tab` to return a list item to a paragraph.

But it seems like the `tab` behavior is more specific about the location of the cursor, and a few other strange things going on.

**Comment by SamyPesse** [comment]
The behavior you are describing looks like the one I'll also expect 👍 

This plugin is still an early WIP.

I'll have time to work more on Slate and the integration in our app next week. In the mid-time feel free to make a PR if you have ideas on how to implement these behaviours :)

----

PS: For our application, we want list items to be contains for blocks (since we are editing Markdown):

```
<li>Hello</li>

=> list_item<block> -> unstyled<block> -> text<text>

<li><p>Hello</p></li>

=> list_item<block> -> paragraph<block> -> text<text>
```

Are you expecting the same for your app? Maybe this plugin can support both.

**Comment by mull** [comment]
@SamyPesse looking at the example linked in the readme the markup is also simply incorrect. When pressing tab when focused on the last item in this example:

```html
<ul>
  <li>hi</li>
  <li></li>
</ul>
```

The output is:

```html
<ul>
  <li>hi</li>
  <li><ul><li></li></ul></li>
</ul>
```

Whereas it should be actually adding a `<ul>` to the first `<li>` like so:

```html
<ul>
  <li>hi
    <ul><li></li></ul>
  </li>
</ul>
```

Don't you agree? I'm learning the transform API myself right now so I'm not entirely sure how to go about it.

**Comment by SamyPesse** [comment]
@mull Yes you're right, but the `hi` should be wrapped in a block (provided as an option, ex: `paragraph`), because otherwise a `text` node will be the sibling of a `block` node.

So the final markup should be:

```html
<ul>
  <li>
    <p>hi</p>
    <ul><li></li></ul>
  </li>
</ul>
```

**Comment by mull** [comment]
Is it not possible to have a text node as sibling? Sounds entirely fine to me :)

**Comment by Soreine** [comment]
I have made a bunch of change to the plugin (see recent closed PR), and implemented schema normalization rules. The live example is updated with the last changes on master. I would be interested to know about your opinion on the updated behavior.

**Comment by mull** [comment]
Tab behavior behaves exactly like expected!

**Comment by ianstormtaylor** [comment]
Looks exactly like I'd expect now! Thanks @Soreine 😄
