### ISSUE TITLE
Merging of Adjacent Lists

### ISSUE THREAD

**Issue by eugenkiss** [GitbookIO/slate-edit-list#30]
I think in certain situations adjacent lists should be merged. See the following video: https://streamable.com/l6rpl

The problem is basically the that you can go from

```
<ul>
  <li>
  <li>
  <li>
<ul>
```

to

```
<ul>
  <li>
  <li>
</ul>
<ul>
  <li>
<ul>
```

without actually intending it.

Here's a gomix for reproduction: 
* https://receptive-glazer.gomix.me/
* https://gomix.com/#!/project/receptive-glazer

Probably a more general issue.

**Comment by SamyPesse** [comment]
Yes, except for lists of different types. 

It'll match the `markup-it` / markdown behaviour: https://github.com/GitbookIO/markup-it/issues/58
