### ISSUE TITLE
A schema rule could not be validated after sufficient iterations

### ISSUE THREAD

**Issue by Slapbox** [GitbookIO/slate-edit-list#31]
`normalize.js:213 Uncaught Error: A schema rule could not be validated after sufficient iterations. This is usually due to a 'rule.validate' or 'rule.normalize' function of a schema being incorrectly written, causing an infinite loop.`

I have tried this plugin with no other plugins (except for one that makes `Ctrl+O` set a the block type to `ol_list`) and it still gives me this error. I can insert list blocks when I disable this plugin, but not with it on.

Any ideas?

Running the latest version of Slate.

**Comment by Soreine** [comment]
Could you provide an example to reproduce the bug? A Slate document, and the code for initializing the plugin and inserting a list?

**Comment by Soreine** [comment]
I have made a fix for the schema rules. It might have solved your problem.
