### ISSUE TITLE
getCurrentItem in fresh lists

### ISSUE THREAD

**Issue by Mangatt** [GitbookIO/slate-edit-list#33]
Hi,
when I wrap Blocks in list and I run getCurrentItem for that state, it returns null even thought selection is clearly in that new list.

When I change selection, it works fine.

**Comment by Soreine** [comment]
Can you reproduce it through a unit test, in the published example, or an online example of yours?

**Comment by Mangatt** [comment]
After some research I think that this actually is Slate issue. I'm closing this issue.
