### ISSUE TITLE
wrapInList for expanded selection

### ISSUE THREAD

**Issue by Mangatt** [GitbookIO/slate-edit-list#34]
Hi,
when I run wrapInList at selection across multiple blocks, it creates single list item in list.

I think that correct behavior should be to create list item for each of selected blocks and wrap those in list. It works like that even at Rich Text example of Slate http://slatejs.org/#/rich-text

**Comment by Soreine** [comment]
Definitely.

Done by 47d1aff
Published as `0.6.0`
