### ISSUE TITLE
List item with multiple blocks, last empty block outdents

### ISSUE THREAD

**Issue by wells** [GitbookIO/slate-edit-list#41]
Place the cursor in the last block of a multi list item. When the last block in the list item is an empty paragraph, hit the enter key. The expected behavior is to create a new list item below the current one. Instead, the current multi block list item is outdented. 

If the last block in the list item has content, a new list item is created below the initial multi block list item. This is an edge case that is totally worth eliminating.

Initial State:
```
* list item
  > with multiple blocks (can just be paragraphs)
  <cursor at empty paragraph>
* list item
```

Result:
```
list item

> with multiple block types

<cursor at empty paragraph>

* list item
```

Example Gif:
![](http://i.giphy.com/l0Ex0iKlXXYdM4nbW.gif)

**Comment by Soreine** [comment]
Thank you for reporting. Fixed in `0.5.7` by https://github.com/GitbookIO/slate-edit-list/pull/39
