### ISSUE TITLE
Bug: Incorrect list item creation under certain circumstances.

### ISSUE THREAD

**Issue by deep-c** [GitbookIO/slate-edit-list#46]
Hi,

https://gitbookio.github.io/slate-edit-list/

If you place your cursor at the end of this line for example `Third item in the list, with a nested list` and press enter a new child item is created however it looks like another parent list is created at the same level of what use to be the first child `First item in the nested list`. 

I would presume what should occur is that it would just create a new list item at the same level of the item enter was pressed on.

On another note, is it possible to disable or prevent certain list edit behaviour occuring. For example i would like to stop the block splitting behaviour being possible (shift + enter).

Thanks

**Comment by ncammarata** [comment]
Also ran into this today as well. Regarding your sidenote, @deep-c, comment out https://github.com/GitbookIO/slate-edit-list/blob/95d758a3e0a29e42cc3b23d768fc182eedb53597/lib/onEnter.js#L17-L19 to remove the shift-enter functionality (I'm assuming here you want shift-enter to create a new item)

**Comment by Soreine** [comment]
The bug should be fixed.
I opened an issue #59 concerning behavior options
