### ISSUE TITLE
Schema no longer supports rules

### ISSUE THREAD

**Issue by RyanMacG** [GitbookIO/slate-edit-list#57]
As of last week/version 0.28.0 the Schema object no longer supports rules as it did previously - more info here https://github.com/ianstormtaylor/slate/blob/master/packages/slate/Changelog.md#0280--october-25-2017

The line that seems to be causing this issue is - https://github.com/GitbookIO/slate-edit-list/blob/1b191b226d9ac08b9a0a09e20332a1b545abf926/lib/makeSchema.js#L10

**Comment by Soreine** [comment]
Closed by #58
