### ISSUE TITLE
Deprecation (slate@0.32.0): The `kind` property of Slate objects has been renamed to `object`

### ISSUE THREAD

**Issue by bengotow** [GitbookIO/slate-edit-list#62]
Will submit a PR to fix this if I get a chance this weekend!

**Comment by zhujinxuan** [comment]
https://github.com/GitbookIO/slate-edit-list/pull/64

**Comment by svenadlung** [comment]
Even after updating the package, the error still persist for me. Any suggestions?

**Comment by zhujinxuan** [comment]
Can you look at your other parts of the code?  I searched the slate-edit-list but I cannot see `kind` in the code base

**Comment by svenadlung** [comment]
Well, it's definitely this plugin. Just removed my node_modules and reinstalled. It's still having the `kind` in the dist files of the npm package. Something went wrong with building the package?

**Comment by zhujinxuan** [comment]
@svenadlung  Is the slate-edit-list version as 0.11.0 in your package.json?

**Comment by svenadlung** [comment]
@zhujinxuan yes it is :(

**Comment by zhujinxuan** [comment]
I have also tried, and find that my dist is also `kind`....LOL

@Soreine Could you have a look at package.json whether the `prepublishOnly` has bugs before publishing?

**Comment by zhujinxuan** [comment]
@svenadlung  I think it is my problem of package.json.  I should not use `prepublishOnly` that without checking yarn compatibility.

**Comment by Soreine** [comment]
0.11.2 should be correctly published
