### ISSUE TITLE
Why item node should contain only block objects?

### ISSUE THREAD

**Issue by Fire7** [GitbookIO/slate-edit-list#70]
https://github.com/GitbookIO/slate-edit-list/blob/master/lib/validation/schema.js#L14

Why not inlines?
```
nodes: [{ objects: ['block', 'inline'] }],
```
I can make a pr with this, if it is ok.

**Comment by zhujinxuan** [comment]
I think inline objects should be excluded.  
If the item is a text block, then it should include only inlines and texts; if the item is a container block, it should include only blocks.

**Comment by Soreine** [comment]
Yes, I think it's a good practice to have blocks that can either contain other blocks, or contain inlines/texts, but never a mix of these. Especially since a default rule in Slate is for blocks to never contain both blocks and inlines at any given time.
