### ISSUE TITLE
getHighestSelectedBlocks() broken due to slate update

### ISSUE THREAD

**Issue by PortableSteve** [GitbookIO/slate-edit-list#75]
As of this recent change, `Node.getPath()` now returns an immutable List:
https://github.com/ianstormtaylor/slate/pull/1997

This breaks `getHighestSelectedBlocks()` in wrapInList.js (and possible other things) since `startPath[0]` and `endPath[0]` are now undefined. As a result, `wrapInList()` creates the list block, but does not create any list items.

**Comment by PortableSteve** [comment]
Of course this is for the just released slate 0.36.0, not the 0.32.0 that is specified in package.json. :facepalm:

**Comment by Soreine** [comment]
No problem @PortableSteve
We can open an issue to release a 0.36 compatible version :)
