### ISSUE TITLE
Still Maintained? 

### ISSUE THREAD

**Issue by brycehill** [GitbookIO/slate-edit-list#87]
Since gitbook has moved to only supporting their own fork of slate, does that mean this plugin will no longer receive updates to support the current versions of slate? 

I see there are a few of issues labeled with ["Upgrade Slate"](https://github.com/GitbookIO/slate-edit-list/issues?q=is%3Aissue+is%3Aopen+label%3Aupgrade-slate). Are those planned to be resolved or should we explore alternative plugins?

I also found this [fork](https://github.com/frontapp/slate-edit-list) while digging through the issues. Is there a plan to incorporate the changes made there into this repo or should we abandon this plugin for that fork?

**Comment by PeterKottas** [comment]
Hi there, I as well was struggling with this, trying to find a solution, but at the end of the day, I've ended up doing the work myself. Here's the end result. https://github.com/guestbell/slate-plugins, hope it works for you, if not, open an issue ;)

**Comment by PeterKottas** [comment]
Also this issue should probably be closed as it doesn't seem like it will ever be resolved.

**Comment by Soreine** [comment]
Since we have forked Slate, we don't plan on maintaining this plugin for the original Slate.
You can indeed look at forks of this plugins, or ask around in Slate's Slack community for list plugins.
